CREATE DOMAIN e164_country_code
AS smallint;

ALTER DOMAIN e164_country_code
ADD CONSTRAINT e164_country_code_ck CHECK (VALUE >= 1 AND VALUE <= 999);

CREATE TYPE continent
AS ENUM ('Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America');

CREATE TABLE e164_country_codes
(
	country_code e164_country_code NOT NULL,
	country text NOT NULL,
	continent continent NOT NULL,
	flag text NOT NULL
);

ALTER TABLE e164_country_codes
ADD CONSTRAINT e164_country_codes_country_code_pk PRIMARY KEY (country_code),
ADD CONSTRAINT e164_country_codes_country_uq UNIQUE (country),
ADD CONSTRAINT e164_country_codes_flag_uq UNIQUE (flag);

INSERT INTO e164_country_codes VALUES
(1, 'Canada / United States', 'North America', '🇨🇦 / 🇺🇸'),
(7, 'Kazakhstan / Russia', 'Asia', '🇰🇿 / 🇷🇺'),
(20, 'Egypt', 'Africa', '🇪🇬'),
(27, 'South Africa', 'Africa', '🇿🇦'),
(30, 'Greece', 'Europe', '🇬🇷 🇪🇺'),
(31, 'Netherlands', 'Europe', '🇳🇱 🇪🇺'),
(32, 'Belgium', 'Europe', '🇧🇪 🇪🇺'),
(33, 'France', 'Europe', '🇫🇷 🇪🇺'),
(34, 'Spain', 'Europe', '🇪🇸 🇪🇺'),
(36, 'Hungary', 'Europe', '🇭🇺 🇪🇺'),
(39, 'Italy', 'Europe', '🇮🇹 🇪🇺'),
(40, 'Romania', 'Europe', '🇷🇴 🇪🇺'),
(41, 'Switzerland', 'Europe', '🇨🇭'),
(43, 'Austria', 'Europe', '🇦🇹 🇪🇺'),
(44, 'United Kingdom', 'Europe', '🇬🇧'),
(45, 'Denmark', 'Europe', '🇩🇰 🇪🇺'),
(46, 'Sweden', 'Europe', '🇸🇪 🇪🇺'),
(47, 'Norway', 'Europe', '🇳🇴'),
(48, 'Poland', 'Europe', '🇵🇱 🇪🇺'),
(49, 'Germany', 'Europe', '🇩🇪 🇪🇺'),
(51, 'Peru', 'South America', '🇵🇪'),
(52, 'Mexico', 'North America', '🇲🇽'),
(53, 'Cuba', 'North America', '🇨🇺'),
(54, 'Argentina', 'South America', '🇦🇷'),
(55, 'Brazil', 'South America', '🇧🇷'),
(56, 'Chile', 'South America', '🇨🇱'),
(57, 'Colombia', 'South America', '🇨🇴'),
(58, 'Venezuela', 'South America', '🇻🇪'),
(60, 'Malaysia', 'Asia', '🇲🇾'),
(61, 'Australia', 'Oceania', '🇦🇺'),
(62, 'Indonesia', 'Asia', '🇮🇩'),
(63, 'Philippines', 'Asia', '🇵🇭'),
(64, 'New Zealand', 'Oceania', '🇳🇿'),
(65, 'Singapore', 'Asia', '🇸🇬'),
(66, 'Thailand', 'Asia', '🇹🇭'),
(81, 'Japan', 'Asia', '🇯🇵'),
(82, 'South Korea', 'Asia', '🇰🇷'),
(84, 'Vietnam', 'Asia', '🇻🇳'),
(86, 'China', 'Asia', '🇨🇳'),
(90, 'Turkey', 'Asia', '🇹🇷'),
(91, 'India', 'Asia', '🇮🇳'),
(92, 'Pakistan', 'Asia', '🇵🇰'),
(93, 'Afghanistan', 'Asia', '🇦🇫'),
(94, 'Sri Lanka', 'Asia', '🇱🇰'),
(95, 'Myanmar', 'Asia', '🇲🇲'),
(98, 'Iran', 'Asia', '🇮🇷'),
(211, 'South Sudan', 'Africa', '🇸🇸'),
(212, 'Morocco', 'Africa', '🇲🇦'),
(213, 'Algeria', 'Africa', '🇩🇿'),
(216, 'Tunisia', 'Africa', '🇹🇳'),
(218, 'Libya', 'Africa', '🇱🇾'),
(220, 'Gambia', 'Africa', '🇬🇲'),
(221, 'Senegal', 'Africa', '🇸🇳'),
(222, 'Mauritania', 'Africa', '🇲🇷'),
(223, 'Mali', 'Africa', '🇲🇱'),
(224, 'Guinea', 'Africa', '🇬🇳'),
(225, 'Ivory Coast', 'Africa', '🇨🇮'),
(226, 'Burkina Faso', 'Africa', '🇧🇫'),
(227, 'Niger', 'Africa', '🇳🇪'),
(228, 'Togo', 'Africa', '🇹🇬'),
(229, 'Benin', 'Africa', '🇧🇯'),
(230, 'Mauritius', 'Africa', '🇲🇺'),
(231, 'Liberia', 'Africa', '🇱🇷'),
(232, 'Sierra Leone', 'Africa', '🇸🇱'),
(233, 'Ghana', 'Africa', '🇬🇭'),
(234, 'Nigeria', 'Africa', '🇳🇬'),
(235, 'Chad', 'Africa', '🇹🇩'),
(236, 'Central African Republic', 'Africa', '🇨🇫'),
(237, 'Cameroon', 'Africa', '🇨🇲'),
(238, 'Cape Verde', 'Africa', '🇨🇻'),
(239, 'São Tomé and Príncipe', 'Africa', '🇸🇹'),
(240, 'Equatorial Guinea', 'Africa', '🇬🇶'),
(241, 'Gabon', 'Africa', '🇬🇦'),
(242, 'Congo (Republic)', 'Africa', '🇨🇬'),
(243, 'Congo (Democratic Republic)', 'Africa', '🇨🇩'),
(244, 'Angola', 'Africa', '🇦🇴'),
(245, 'Guinea-Bissau', 'Africa', '🇬🇼'),
(246, 'British Indian Ocean Territory', 'Asia', '🇮🇴'),
(247, 'Ascension Island', 'Africa', '🇦🇨'),
(248, 'Seychelles', 'Africa', '🇸🇨'),
(249, 'Sudan', 'Africa', '🇸🇩'),
(250, 'Rwanda', 'Africa', '🇷🇼'),
(251, 'Ethiopia', 'Africa', '🇪🇹'),
(252, 'Somalia', 'Africa', '🇸🇴'),
(253, 'Djibouti', 'Africa', '🇩🇯'),
(254, 'Kenya', 'Africa', '🇰🇪'),
(255, 'Tanzania', 'Africa', '🇹🇿'),
(256, 'Uganda', 'Africa', '🇺🇬'),
(257, 'Burundi', 'Africa', '🇧🇮'),
(258, 'Mozambique', 'Africa', '🇲🇿'),
(260, 'Zambia', 'Africa', '🇿🇲'),
(261, 'Madagascar', 'Africa', '🇲🇬'),
(262, 'Réunion', 'Africa', '🇷🇪'),
(263, 'Zimbabwe', 'Africa', '🇿🇼'),
(264, 'Namibia', 'Africa', '🇳🇦'),
(265, 'Malawi', 'Africa', '🇲🇼'),
(266, 'Lesotho', 'Africa', '🇱🇸'),
(267, 'Botswana', 'Africa', '🇧🇼'),
(268, 'Eswatini', 'Africa', '🇸🇿'),
(269, 'Comoros', 'Africa', '🇰🇲'),
(290, 'Saint Helena', 'Africa', '🇸🇭'),
(291, 'Eritrea', 'Africa', '🇪🇷'),
(297, 'Aruba', 'South America', '🇦🇼'),
(298, 'Faroe Islands', 'Europe', '🇫🇴'),
(299, 'Greenland', 'North America', '🇬🇱'),
(350, 'Gibraltar', 'Europe', '🇬🇮'),
(351, 'Portugal', 'Europe', '🇵🇹 🇪🇺'),
(352, 'Luxembourg', 'Europe', '🇱🇺 🇪🇺'),
(353, 'Ireland', 'Europe', '🇮🇪 🇪🇺'),
(354, 'Iceland', 'Europe', '🇮🇸'),
(355, 'Albania', 'Europe', '🇦🇱'),
(356, 'Malta', 'Europe', '🇲🇹 🇪🇺'),
(357, 'Cyprus', 'Asia', '🇨🇾 🇪🇺'),
(358, 'Finland', 'Europe', '🇫🇮 🇪🇺'),
(359, 'Bulgaria', 'Europe', '🇧🇬 🇪🇺'),
(370, 'Lithuania', 'Europe', '🇱🇹 🇪🇺'),
(371, 'Latvia', 'Europe', '🇱🇻 🇪🇺'),
(372, 'Estonia', 'Europe', '🇪🇪 🇪🇺'),
(373, 'Moldova', 'Europe', '🇲🇩'),
(374, 'Armenia', 'Asia', '🇦🇲'),
(375, 'Belarus', 'Europe', '🇧🇾'),
(376, 'Andorra', 'Europe', '🇦🇩'),
(377, 'Monaco', 'Europe', '🇲🇨'),
(378, 'San Marino', 'Europe', '🇸🇲'),
(379, 'Vatican City', 'Europe', '🇻🇦'),
(380, 'Ukraine', 'Europe', '🇺🇦'),
(381, 'Serbia', 'Europe', '🇷🇸'),
(382, 'Montenegro', 'Europe', '🇲🇪'),
(383, 'Kosovo', 'Europe', '🇽🇰'),
(385, 'Croatia', 'Europe', '🇭🇷 🇪🇺'),
(386, 'Slovenia', 'Europe', '🇸🇮 🇪🇺'),
(387, 'Bosnia and Herzegovina', 'Europe', '🇧🇦'),
(389, 'North Macedonia', 'Europe', '🇲🇰'),
(420, 'Czechia', 'Europe', '🇨🇿 🇪🇺'),
(421, 'Slovakia', 'Europe', '🇸🇰 🇪🇺'),
(423, 'Liechtenstein', 'Europe', '🇱🇮'),
(500, 'Falkland Islands / South Georgia and the South Sandwich Islands', 'South America', '🇫🇰'),
(501, 'Belize', 'North America', '🇧🇿'),
(502, 'Guatemala', 'North America', '🇬🇹'),
(503, 'El Salvador', 'North America', '🇸🇻'),
(504, 'Honduras', 'North America', '🇭🇳'),
(505, 'Nicaragua', 'North America', '🇳🇮'),
(506, 'Costa Rica', 'North America', '🇨🇷'),
(507, 'Panama', 'North America', '🇵🇦'),
(508, 'Saint-Pierre and Miquelon', 'North America', '🇵🇲'),
(509, 'Haiti', 'North America', '🇭🇹'),
(590, 'Guadeloupe', 'North America', '🇬🇵'),
(591, 'Bolivia', 'South America', '🇧🇴'),
(592, 'Guyana', 'South America', '🇬🇾'),
(593, 'Ecuador', 'South America', '🇪🇨'),
(594, 'French Guiana', 'South America', '🇬🇫'),
(595, 'Paraguay', 'South America', '🇵🇾'),
(596, 'Martinique', 'North America', '🇲🇶'),
(597, 'Suriname', 'South America', '🇸🇷'),
(598, 'Uruguay', 'South America', '🇺🇾'),
(599, 'Bonaire / Curaçao / Saba / Sint Eustatius', 'North America', '🇧🇶 / 🇨🇼'),
(670, 'Timor-Leste', 'Asia', '🇹🇱'),
(672, 'Norfolk Island', 'Oceania', '🇳🇫'),
(673, 'Brunei', 'Asia', '🇧🇳'),
(674, 'Nauru', 'Oceania', '🇳🇷'),
(675, 'Papua New Guinea', 'Oceania', '🇵🇬'),
(676, 'Tonga', 'Oceania', '🇹🇴'),
(677, 'Solomon Islands', 'Oceania', '🇸🇧'),
(678, 'Vanuatu', 'Oceania', '🇻🇺'),
(679, 'Fiji', 'Oceania', '🇫🇯'),
(680, 'Palau', 'Oceania', '🇵🇼'),
(681, 'Wallis and Futuna', 'Oceania', '🇼🇫'),
(682, 'Cook Islands', 'Oceania', '🇨🇰'),
(683, 'Niue', 'Oceania', '🇳🇺'),
(685, 'Samoa', 'Oceania', '🇼🇸'),
(686, 'Kiribati', 'Oceania', '🇰🇮'),
(687, 'New Caledonia', 'Oceania', '🇳🇨'),
(688, 'Tuvalu', 'Oceania', '🇹🇻'),
(689, 'French Polynesia', 'Oceania', '🇵🇫'),
(690, 'Tokelau', 'Oceania', '🇹🇰'),
(691, 'Micronesia', 'Oceania', '🇫🇲'),
(692, 'Marshall Islands', 'Oceania', '🇲🇭'),
(850, 'North Korea', 'Asia', '🇰🇵'),
(852, 'Hong Kong', 'Asia', '🇭🇰'),
(853, 'Macau', 'Asia', '🇲🇴'),
(855, 'Cambodia', 'Asia', '🇰🇭'),
(856, 'Laos', 'Asia', '🇱🇦'),
(880, 'Bangladesh', 'Asia', '🇧🇩'),
(886, 'Taiwan', 'Asia', '🇹🇼'),
(960, 'Maldives', 'Asia', '🇲🇻'),
(961, 'Lebanon', 'Asia', '🇱🇧'),
(962, 'Jordan', 'Asia', '🇯🇴'),
(963, 'Syria', 'Asia', '🇸🇾'),
(964, 'Iraq', 'Asia', '🇮🇶'),
(965, 'Kuwait', 'Asia', '🇰🇼'),
(966, 'Saudi Arabia', 'Asia', '🇸🇦'),
(967, 'Yemen', 'Asia', '🇾🇪'),
(968, 'Oman', 'Asia', '🇴🇲'),
(970, 'Palestine', 'Asia', '🇵🇸'),
(971, 'United Arab Emirates', 'Asia', '🇦🇪'),
(972, 'Israel', 'Asia', '🇮🇱'),
(973, 'Bahrain', 'Asia', '🇧🇭'),
(974, 'Qatar', 'Asia', '🇶🇦'),
(975, 'Bhutan', 'Asia', '🇧🇹'),
(976, 'Mongolia', 'Asia', '🇲🇳'),
(977, 'Nepal', 'Asia', '🇳🇵'),
(992, 'Tajikistan', 'Asia', '🇹🇯'),
(993, 'Turkmenistan', 'Asia', '🇹🇲'),
(994, 'Azerbaijan', 'Asia', '🇦🇿'),
(995, 'Georgia', 'Asia', '🇬🇪'),
(996, 'Kyrgyzstan', 'Asia', '🇰🇬'),
(998, 'Uzbekistan', 'Asia', '🇺🇿');